apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: {{ .Values.argocdNamespace }}
spec:
  sourceRepos:
    - "*"
  destinations:
{{- range .Values.namespaces }}
    - namespace: {{ . | quote }}
      server: https://kubernetes.default.svc
{{- end }}
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
