{{- range $name, $svc := .Values.services }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth2-forward-auth-{{ $name }}
  namespace: sso
  labels:
    app: oauth2-proxy-{{ $name }}
spec:
  forwardAuth:
    address: http://oauth2-proxy-{{ $name }}.sso.svc.cluster.local:{{ $svc.port }}/
    trustForwardHeader: true
    authResponseHeaders:
#      - X-Auth-Request-User
#      - X-Auth-Request-Email
#      - X-Auth-Request-Groups
      - X-Forwarded-User
      - X-Forwarded-Email
      - X-Forwarded-Preferred-Username
      - X-Forwarded-Groups
      - Authorization
{{- end }}
