{{- range $name, $svc := .Values.services }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth2-forward-auth-{{ $name }}
  namespace: sso
  labels:
    app: oauth2-proxy-{{ $name }}
spec:
  forwardAuth:
    address: http://oauth2-proxy-{{ $name }}.sso.svc.cluster.local:{{ $svc.port }}/
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Auth-Request-Groups
      - X-Auth-Request-Preferred-Username
      # these are not currently required, becuase of a OAuthProxy bug not setting them
      # however I keep them here in case oauth2proxy suddenly fixes the bug
      - X-Forwarded-User
      - X-Forwarded-Email
      - X-Forwarded-Preferred-Username
      - X-Forwarded-Groups
      - Authorization

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth2-forwarded-headers-{{ $name }}
  namespace: sso
spec:
  # FIXME: if oauth proxy ever fixes the above bug, remove this
  plugin:
    traefik-transformer:
      transformers:
        - replaceHeader:
            name: X-Forwarded-Preferred-Username
            expression: 'RequestHeader("X-Auth-Request-Preferred-Username")'
        - replaceHeader:
            name: X-Forwarded-Groups
            expression: 'RequestHeader("X-Auth-Request-Groups")'
{{- end }}
