{{- range $name, $svc := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy-{{ $name }}
  labels:
    app: oauth2-proxy-{{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy-{{ $name }}
  template:
    metadata:
      labels:
        app: oauth2-proxy-{{ $name }}
    spec:
      containers:
        - name: oauth2-proxy
          image: {{ $.Values.oauth2Proxy.image }}
          args:
            - --http-address=0.0.0.0:{{ $svc.port }}
            {{- with $svc.skips }}
            {{- range . }}
            - "--skip-auth-route={{ . }}"
            {{- end }}
            {{- end }}
          env:
            - name: OAUTH2_PROXY_SCOPE
              value: {{ $.Values.oauth2Proxy.defaults.scope }}
            #- name: OAUTH2_PROXY_UPSTREAMS
            #  value: http:// {{ $.Values.globalNodeIP }}:{{ $svc.port }} #{{- if $svc.overwrite }}{{ $svc.overwrite }}{{- else }}http://{{ $.Values.globalNodeIP | default "127.0.0.1" }}:{{ $svc.port }}/{{- end }}
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: '*'
            - name: OAUTH2_PROXY_PROVIDER
              value: {{ $.Values.oauth2Proxy.defaults.provider }}
            - name: OAUTH2_PROXY_PROVIDER_DISPLAY_NAME
              value: {{ $.Values.oauth2Proxy.defaults.providerDisplayName }}
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              value: {{ $.Values.keycloak.issuerUrl }}
            - name: OAUTH2_PROXY_OIDC_EMAIL_CLAIM
              value: {{ $.Values.oauth2Proxy.defaults.oidcEmailClaim }}
            - name: OAUTH2_PROXY_SET_XAUTHREQUEST
              value: "true"
            - name: OAUTH2_PROXY_SESSION_STORE_TYPE
              value: redis
            - name: OAUTH2_PROXY_REDIS_CONNECTION_URL
              value: {{ $.Values.oauth2Proxy.redisUrl }}
            - name: OAUTH2_PROXY_COOKIE_REFRESH
              value: 17m
            - name: OAUTH2_PROXY_COOKIE_NAME
              value: SESSION
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom: 
                secretKeyRef:
                    name: {{ $svc.secret_name }}
                    key: party-secret
            - name: OAUTH2_PROXY_REVERSE_PROXY
              value: {{ $.Values.oauth2Proxy.defaults.reverseProxy | quote }}
            - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
              value: {{ $.Values.oauth2Proxy.defaults.skipProviderButton | quote }}
            - name: OAUTH2_PROXY_WHITELIST_DOMAIN
              value: {{ $.Values.oauth2Proxy.whitelistDomains }}
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom: 
                secretKeyRef:
                    name: {{ $svc.secret_name }}
                    key: client-id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom: 
                secretKeyRef:
                    name: {{ $svc.secret_name }}
                    key: client-secret
            - name: OAUTH2_PROXY_REDIRECT_URL
              valueFrom: 
                secretKeyRef:
                    name: {{ $svc.secret_name }}
                    key: redirect_uris
            - name: OAUTH2_PROXY_ALLOWED_GROUPS
              valueFrom: 
                secretKeyRef:
                    name: {{ $svc.secret_name }}
                    key: groups
          ports:
            - containerPort: {{ $svc.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-{{ $name }}
  labels:
    app: oauth2-proxy-{{ $name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      protocol: TCP
  selector:
    app: oauth2-proxy-{{ $name }}
{{- end }}
