{{- if .Values.oauth2Proxy.redis.enabled }}
{{- range $name, $svc := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $svc.namespace }}
  name: redis-{{ $name }}
spec:
  selector:
    matchLabels:
      app: redis-{{ $name }}
  template:
    metadata:
      labels:
        app: redis-{{ $name }}
    spec:
      containers:
        - name: redis
          image: redis:latest
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $svc.namespace }}
  name: redis-{{ $name }}
spec:
  ports:
    - port: 6379
  selector:
    app: redis-{{ $name }}
{{- end }}
{{- end }}
