apiVersion: v1
kind: ConfigMap
metadata:
  name: docspell-config
  namespace: docspell
data:
  application.conf.tpl: |
    docspell.server {

      app-name = "Atlantis Documents"
      oidc-auto-redirect = true
      base-url = "https://documents.services.atlantishq.de"

      jdbc {
        url = "jdbc:postgresql://$DB_HOST:5432/$DB_NAME"
        user = "$DB_USER"
        password = "$DB_PASSWORD"
      }

      files {
        default-store = "s3"
        stores {
          s3 {
            enabled = true
            type = "s3"
            endpoint = "$S3_ENDPOINT"
            bucket = "$S3_BUCKET"
            access-key = "$S3_ACCESS_KEY"
            secret-key = "$S3_SECRET_KEY"
            region = "$S3_REGION"
            path-style-access = true
          }
        }
      }

      openid = [
        {
          enabled = true
          display = "AtlantisHQ Accounts"
          provider = {
            provider-id = "keycloak"
            client-id = "$OIDC_CLIENT_ID"
            client-secret = "$OIDC_CLIENT_SECRET"
            scope = "openid profile email"
            authorize-url = "https://keycloak.atlantishq.de/realms/master/protocol/openid-connect/auth"
            token-url = "https://keycloak.atlantishq.de/realms/master/protocol/openid-connect/token"
            user-url = "https://keycloak.atlantishq.de/realms/master/protocol/openid-connect/userinfo"
            sign-key = """"
    -----BEGIN CERTIFICATE-----                                                   
    MIICmzCCAYMCBgGNXNpYjzANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAZtYXN0ZXIwHhcNMjQwMTMxMDAwODQ5WhcNMzQwMTMxMDAxMDI5WjARMQ8wDQYDVQQDDAZtYXN0ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCToKsmMLkwmq/9Tvvhn8xIrDAHrARYT7v/iv9pjFUrcSUshaAIquej5n74/7wAYFnoRN1/5SEslPpuLCyUiTPRWPnHk6pzmYOM4ry1wGMEuGEdRNSYUfQmmo/NmLH1zKcJ+WU8A0c7oSHQjnNSOurT+xtsqVKfQam4ZCev4cnAri+MfBXCaayi6TckcjAsWrJbZsNvkelv1WjFNLggTiNL4EMmXjgjEMcH0Drx7e79D2ocwT4wSwC+dnY3ELu9/5cNGK00ieYabOJ/flDHiqDLNraO0D1BSaCV/zncw3cHDA60Nl3XnJ6UuqKRQLhJZKNn6Z3q2WZEKTCCT+/145idAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAGZZJe6kxcMNJFacgz4uKG9WAL+1IjDt/Ptsv8OXvB1+u0CS6JlqQDsTBU+Wpt6RXMG72nepkkpdwgXwSGVOJFrQh0Da5BJUEwYv7gZZXP5MeQVzUqjUPu7M8ZVyUba9ezDruBDmNk+tkSEFX6g1SXXuh3pusBk09jAoFrxyNk/M+9MU6PA3tOhYQxyNjnAnLTMehKVkgDLvUvuH2cxOun0q4C6F73a0DSlcI7fEytftojG8FKFxHXmPVxcGx6m2KzzlqcSS68h7o36ozZDhbFTxEsyjcldW85ea01JWDF7uKMMGq+XTtubPLY9BrT2Dv252npvIaX3HRaYAcABHKuQ=
    -----END CERTIFICATE-----
    """"
            sig-algo = "RS256"
          }
          collective-key = "lookup:groups"
          user-key = "preferred_username"
        }
      ]

      bind {
        address = "0.0.0.0"
        port = 7880
      }

      postgresql = {
        use-default-connection = true
      }
    }
