---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat

  template:
    metadata:
      labels:
        app: filebeat

    spec:
      serviceAccountName: filebeat

      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.19.15

          args:
            - -c
            - /etc/filebeat.yml
            - -e

          securityContext:
            runAsUser: 0

          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          volumeMounts:
            - name: config
              mountPath: /etc/filebeat.yml
              subPath: filebeat.yml
              readOnly: true

            - name: logs
              mountPath: /var/log
              readOnly: true

            - name: data
              mountPath: /usr/share/filebeat/data

      volumes:
        - name: config
          configMap:
            name: filebeat

        - name: logs
          hostPath:
            path: /var/log

        - name: data
          hostPath:
            path: /var/lib/filebeat-data
            type: DirectoryOrCreate
