apiVersion: v2
name: garage-s3
version: 0.1.0
repositories:
  - name: garage
    url: https://git.deuxfleurs.fr/Deuxfleurs/garage.git

releases:
  - name: garage
    chart: ./scripts/helm/garage
    values:
      - values.yaml
