services:
  potaris:
    targetPort: 5000
    hostname: potaris.rancher.katzencluster.atlantishq.de
    image: harbor-registry.atlantishq.de/atlantishq/potaris-next-gen-web
  ax-filmes:
    targetPort: 80
    hostname: ax-films.rancher.katzencluster.atlantishq.de
    image: harbor-registry.atlantishq.de/atlantishq/ax-films
  bento-pdf:
    targetPort: 8080
    hostname: pdf.rancher.katzencluster.atlantishq.de
    image: ghcr.io/alam00000/bentopdf-simple:latest
  webhook-tester:
    targetPort: 8080
    hostname: webhook-tester.rancher.katzencluster.atlantishq.de
    image: ghcr.io/tarampampam/webhook-tester:2
  sector:
    targetPort: 5000
    hostname: sector32.rancher.katzencluster.atlantishq.de
    image: harbor-registry.atlantishq.de/atlantishq/sector32
  serienampel:
    targetPort: 5000
    hostname: serienampel.rancher.katzencluster.atlantishq.de
    image: harbor-registry.atlantishq.de/atlantishq/serienampel:latest
