apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea-runner
  namespace: fleet-local
spec:
  targetNamespace: gitea
  chart: gitea/act-runner
  repo: https://dl.gitea.com/charts/
  valuesFiles:
    - values.yaml
