createClusterRoles: false

global:
  domain: argocd.potaris.de

crds:
  install: true
  keep: true

configs:
  cm:
    url: https://argocd.example.com
    oidc.config: |
      name: Keycloak
      issuer: https://keycloak.atlantishq.de/realms/master
      clientID: argocd
      clientSecret: $oidc-secret.client_secret
      requestedScopes:
        - openid
        - profile
        - email
        - groups
      requestedIDTokenClaims:
        groups:
          essential: true

  params:
    server.insecure: false

  rbac:
    policy.default: role:none
    scopes: '[groups, email]'
    policy.csv: |
      p, role:none, applications, get, __none__, deny

      g, atlantis-admins, role:admin

      p, role:opendesk, applications, get, opendesk/*, allow
      p, role:opendesk, applications, sync, opendesk/*, allow
      p, role:opendesk, applications, action/*, opendesk/*, allow
      p, role:opendesk, logs, get, opendesk/*, allow
      g, opendesk, role:opendesk

controller:
  replicas: 1

repoServer:
  volumes:
    - name: helmfile-cmp-tmp
      emptyDir: {}

  extraContainers:
    - name: helmfile-plugin
      image: travisghansen/argo-cd-helmfile:latest
      imagePullPolicy: IfNotPresent
      command:
        - /var/run/argocd/argocd-cmp-server
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - name: var-files
          mountPath: /var/run/argocd
        - name: plugins
          mountPath: /home/argocd/cmp-server/plugins
        - name: helmfile-cmp-tmp
          mountPath: /tmp

server:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: traefik

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"

    extraTls:
      - hosts:
          - argocd.potaris.de
        secretName: argocd-tls
