apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ntfy-api-ingress
spec:
  rules:
    - host: ntfy-api.rancher.katzencluster.atlantishq.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ntfy-api
                port:
                  number: 50000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: event-dispatcher-ingress
spec:
  rules:
    - host: dispatcher.rancher.katzencluster.atlantishq.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: event-dispatcher
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ntfy-ingress
spec:
  rules:
    - host: push.rancher.katzencluster.atlantishq.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ntfy
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atlantis-verify-ingress
spec:
  rules:
    - host: verify.rancher.katzencluster.atlantishq.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atlantis-verify
                port:
                  number: 5000
