extraVolumes:
  - name: realm-import
    configMap:
      name: keycloak-realm-import

extraVolumeMounts:
  - name: realm-import
    mountPath: /opt/bitnami/keycloak/data/import
    readOnly: true

proxyHeaders: xforwarded

global:
  postgresql:
    image:
        repository: bitnami/postgresql
        tag: latest
    auth:
      password: "test"

auth:
    adminPassword: "test"
extraStartupArgs: "--import-realm"
args:
  - start
  - --import-realm

production: true

proxy: edge


httpRelativePath: /

extraEnvVars:
  - name: KC_HOSTNAME
    value: faf-auth-proxy.services.atlantishq.de
  - name: KC_HOSTNAME_STRICT
    value: "true"

ingress:
  enabled: true
  ingressClassName: traefik

  hostname: faf-auth-proxy.services.atlantishq.de

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

  tls: true
  extraTls:
    - hosts:
        - faf-auth-proxy.services.atlantishq.de
      secretName: faf-auth-proxy-tls
