apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-import
data:
  realm.json: |
    {
      "realm": "atlantis",
      "enabled": true,

      "clients": [
        {
          "clientId": "fa_metrics",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "secret": "${FA_METRICS_CLIENT_SECRET}",
          "redirectUris": [
            "https://fa-metrics.rancher.katzencluster.atlantishq.de/*"
          ]
        },
        {
          "clientId": "mapgen",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "secret": "${MAPGEN_SAAS_CLIENT_SECRET}",
          "redirectUris": [
            "https://mapgen.services.atlantishq.de/*"
          ]
        }
      ],

      "browserFlow": "browser-with-idp",
      "authenticatorConfig": [
        {
          "alias": "idp-redirect",
          "config": {
            "defaultProvider": "faf"
          }
        }
      ],
      "authenticationFlows": [
        {
          "alias": "browser-with-idp",
          "providerId": "basic-flow",
          "topLevel": true,
          "builtIn": false,
          "authenticationExecutions": [
            {
              "authenticator": "auth-cookie",
              "requirement": "ALTERNATIVE",
              "priority": 10
            },
            {
              "authenticator": "identity-provider-redirector",
              "requirement": "ALTERNATIVE",
              "priority": 20,
              "authenticatorConfig": "idp-redirect"
            },
            {
              "authenticator": "auth-username-password-form",
              "requirement": "ALTERNATIVE",
              "priority": 30
            }
          ]
        }
      ],
      "identityProviders": [
        {
          "alias": "faf",
          "displayName": "FAF",
          "internalId": "5a26d541-2374-4a9d-b825-b95501ee7251",
          "providerId": "oidc",
          "enabled": true,
          "updateProfileFirstLoginMode": "on",
          "trustEmail": false,
          "storeToken": false,
          "addReadTokenRoleOnCreate": false,
          "authenticateByDefault": false,
          "linkOnly": false,
          "hideOnLogin": false,
          "config": {
            "userInfoUrl": "https://hydra.faforever.com/userinfo",
            "validateSignature": "true",
            "tokenUrl": "https://hydra.faforever.com/oauth2/token",
            "clientId": "20ca564b-d0d3-445f-8317-ce7cff4f878d",
            "jwksUrl": "https://hydra.faforever.com/.well-known/jwks.json",
            "issuer": "https://hydra.faforever.com",
            "useJwksUrl": "true",
            "pkceEnabled": "false",
            "metadataDescriptorUrl": "https://hydra.faforever.com/.well-known/openid-configuration",
            "authorizationUrl": "https://hydra.faforever.com/oauth2/auth",
            "clientAuthMethod": "client_secret_post",
            "logoutUrl": "https://hydra.faforever.com/oauth2/sessions/logout",
            "syncMode": "LEGACY",
            "clientSecret": "${FAF_OIDC_SECRET}"
          }
        }
      ],
      "identityProviderMappers": [
        {
          "id": "9aebecc3-a1d8-4831-92e1-f649d9e718ce",
          "name": "E-Mail Mapper",
          "identityProviderAlias": "faf",
          "identityProviderMapper": "hardcoded-attribute-idp-mapper",
          "config": {
            "syncMode": "INHERIT",
            "attribute.value": "doesntexist@invalid.atlantishq.de",
            "attribute": "email"
          }
        },
        {
          "id": "acb1f1bf-c5ee-43dc-9aa5-35978fea4eb2",
          "name": "username",
          "identityProviderAlias": "faf",
          "identityProviderMapper": "oidc-user-attribute-idp-mapper",
          "config": {
            "syncMode": "INHERIT",
            "claim": "username",
            "user.attribute": "username"
          }
        },
        {
          "id": "0ebaef33-d45d-487f-bbf4-40d3e773f204",
          "name": "firstname",
          "identityProviderAlias": "faf",
          "identityProviderMapper": "oidc-user-attribute-idp-mapper",
          "config": {
            "syncMode": "INHERIT",
            "claim": "username",
            "user.attribute": "firstName"
          }
        },
        {
          "id": "1bc3fa56-4012-45b2-aa4e-a2f2ca1e6eb3",
          "name": "lastname",
          "identityProviderAlias": "faf",
          "identityProviderMapper": "oidc-user-attribute-idp-mapper",
          "config": {
            "syncMode": "INHERIT",
            "claim": "username",
            "user.attribute": "lastName"
          }
        }
      ],
    }
