apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  admin_user: admin

  ingress_type: ingress
  ingress_annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  ingress_hosts:
    - hostname: awx.rancher.katzencluster.atlantishq.de
      tls_secret: awx-ingress-tls

  postgres_storage_class: longhorn
  postgres_data_volume_init: true

  service_type: ClusterIP
  tls_secret: awx-ingress-tls

  extraEnv:
    - name: SOCIAL_AUTH_OIDC_KEY
      valueFrom:
        secretKeyRef:
          name: awx-oidc-config
          key: client-id

    - name: SOCIAL_AUTH_OIDC_SECRET
      valueFrom:
        secretKeyRef:
          name: awx-oidc-config
          key: client-secret

    - name: SOCIAL_AUTH_OIDC_OIDC_ENDPOINT
      value: "https://keycloak.atlantishq.de/.well-known/openid-configuration"

    - name: SOCIAL_AUTH_OIDC_REDIRECT_URI
      valueFrom:
        secretKeyRef:
          name: awx-oidc-config
          key: redirect_uris

    - name: SOCIAL_AUTH_OIDC_GROUPS_CLAIM
      valueFrom:
        secretKeyRef:
          name: awx-oidc-config
          key: groups

  extra_settings:
    - setting: AUTHENTICATION_BACKENDS
    value: '["social_core.backends.open_id_connect.OpenIdConnectAuth","django.contrib.auth.backends.ModelBackend"]'
