apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  admin_user: admin

  ingress_type: ingress
  ingress_annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  ingress_hosts:
    - hostname: awx.rancher.katzencluster.atlantishq.de
      tls_secret: awx-ingress-tls  # optional, see below

  postgres_storage_class: longhorn
  postgres_data_volume_init: true

  service_type: ClusterIP

  auth_enabled: true
  authentication_backend: oidc

  oauth2_secret: awx-oidc-config

  # Required AWX OIDC settings
  extra_settings:
    - setting: AUTHENTICATION_BACKENDS
      value:
        - social_core.backends.open_id_connect.OpenIdConnectAuth
        - django.contrib.auth.backends.ModelBackend

    - setting: SOCIAL_AUTH_OIDC_KEY
      secret: awx-oidc-config
      secretKey: client-id

    - setting: SOCIAL_AUTH_OIDC_SECRET
      secret: awx-oidc-config
      secretKey: client-secret

    - setting: SOCIAL_AUTH_OIDC_OIDC_ENDPOINT
      value: "https://keycloak.atlantishq.de"

    - setting: SOCIAL_AUTH_OIDC_REDIRECT_URI
      secret: awx-oidc-config
      secretKey: redirect_uris

    - setting: SOCIAL_AUTH_OIDC_GROUPS_CLAIM
      secret: awx-oidc-config
      secretKey: groups
