# =========================
# Global
# =========================
externalURL: https://registry.services.atlantishq.de

harborAdminPassword: ""
existingSecretAdminPassword: harbor-secrets

# =========================
# Expose / Ingress
# =========================
expose:
  type: ingress

  tls:
    enabled: true
    certSource: harbor-tls-le

  ingress:
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt-prod"
      traefik.ingress.kubernetes.io/router.tls: "true"
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"

    hosts:
      core: registry.services.atlantishq.de

# =========================
# External Database
# =========================
database:
  type: external

  internal:
    enabled: false

  external:
    host: postgres.atlantishq.de
    port: 5432

    existingSecret: harbor-db-secret
    existingSecretKey: DB_PASSWORD

    username: harbor

    coreDatabase: harbor
    notaryServerDatabase: harbor_notary_server
    notarySignerDatabase: harbor_notary_signer

    sslmode: require

# =========================
# Redis / Valkey
# =========================
redis:
  type: internal

  internal:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi

    harborDatabaseIndex: "0"
    jobserviceDatabaseIndex: "1"
    registryDatabaseIndex: "2"
    trivyAdapterIndex: "5"
    cacheLayerDatabaseIndex: "0"

# =========================
# Storage (S3)
# =========================
persistence:
  enabled: true

  persistentVolumeClaim:
    registry:
      enabled: false
    jobservice:
      enabled: false
    database:
      enabled: false
    redis:
      enabled: false
    trivy:
      enabled: false

  imageChartStorage:
    type: s3


    s3:
      region: eu-central
      bucket: atlantis-harbor

      regionendpoint: hel1.your-objectstorage.com

      secure: true
      v4auth: true
      #loglevel: debugwithrequestretries
      chunksize: 67108864

      existingSecret: harbor-secrets

# =========================
# Core Components
# =========================
core:
  replicas: 1
  logLevel: info

  # Redis reduces DB activity when many concurrent pushes
  # update quota information for the same project.
  quotaUpdateProvider: redis

jobservice:
  jobLoggers:
    - stdout
  replicas: 1

registry:
  replicas: 1
  resources:
    requests: 250m
    memory: 256Mi
  limit:
    cpu: "2"
    memory: 1Gi

portal:
  replicas: 1

trivy:
  enabled: true

# =========================
# Notary
# =========================
notary:
  enabled: false

# =========================
# Metrics
# =========================
metrics:
  enabled: true
  serviceMonitor:
    enabled: false

# =========================
# Logging
# =========================
logLevel: info

# =========================
# Proxy
# =========================
proxy:
  httpProxy:
  httpsProxy:
  noProxy: 127.0.0.1,localhost,.local,.internal

# =========================
# Internal TLS
# =========================
internalTLS:
  enabled: false

# =========================
# Network policy
# =========================
networkPolicy:
  enabled: false

# =========================
# Harbor application cache
# =========================
cache:
  enabled: true
  expireHours: 24

# =========================
# Authentication
# =========================
authMode: oidc_auth

oidc:
  name: keycloak
  endpoint: https://keycloak.atlantishq.com/realms/master
  clientId: harbor
  clientSecret: ""

  existingSecret: async-icinga-oidc-config
  existingSecretKey: client-secret

  scope: openid,profile,email
  verifyCert: true

  autoOnboard: true
  userClaim: preferred_username

  groupsClaim: groups
  groupFilter: ""

  adminGroup: harbor-admins

  redirectURL: https://registry.services.atlantishq.de/c/oidc/callback
