---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fa-metrics-legacy
  labels:
    app: fa-metrics
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/redirect-entry-point: "https"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - fa-metrics.rancher.katzencluster.atlantishq.de
      secretName: fa-metrics-legacy-redirect-tls
  rules:
    - host: fa-metrics.rancher.katzencluster.atlantishq.de
      http:
        paths:
          - path: /favicon.svg
            pathType: Exact
            backend:
              service:
                name: fa-metrics-frontend
                port:
                  number: 80
