projectName: opendesk
argocdNamespace: argocd
controllerServiceAccount: argocd-application-controller

namespaces:
  - opendesk

sourceRepos:
  - "*"

namespaceResourceWhitelist:
  - group: "*"
    kind: "*"

verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
