apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapgen
  namespace: mapgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mapgen
  template:
    metadata:
      labels:
        app: mapgen
    spec:
      containers:
        - name: frontend
          image: harbor-registry.atlantishq.de/atlantishq/mapgen-as-a-service-server-frontend:latest
          ports:
            - containerPort: 80

        - name: backend
          image: harbor-registry.atlantishq.de/atlantishq/mapgen-as-a-service-server:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: mapgen-db-secret
            - secretRef:
                name: mapgen-secrets
