apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: neroxis-mapgen-worker
spec:
  scaleTargetRef:
    name: neroxis-mapgen-worker

  minReplicaCount: 5
  maxReplicaCount: 15

  pollingInterval: 1

  triggers:
  - type: postgresql
    metadata:
      userName: mapgen
      host: postgres.atlantishq.de
      port: "5432"
      dbName: mapgen
      sslmode: require

      query: |
        SELECT GREATEST(COUNT(*), 1)
        FROM request_queue
        WHERE finished = FALSE

      targetQueryValue: "2"

    authenticationRef:
      name: postgres-auth
