coder:
  env:
    CODER_ACCESS_URL: "https://coder.services.atlantishq.de"

    # OIDC
    CODER_OIDC_ISSUER_URL: "https://keycloak.atlantishq.de/realms/master"
    CODER_OIDC_CLIENT_ID: "coder"
    CODER_OIDC_CLIENT_SECRET: ""

    CODER_OIDC_SCOPES: "openid profile email"
    CODER_OIDC_USERNAME_FIELD: "preferred_username"
    CODER_OIDC_EMAIL_FIELD: "email"

  extraEnv:
      - name: CODER_OIDC_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: coder-oidc-config
            key: client-id
      - name: CODER_OIDC_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: coder-oidc-config
            key: client-secret
      - name: CODER_PG_CONNECTION_URL
        valueFrom:
          secretKeyRef:
            # postgres://coder:password@postgres:5432/coder?sslmode=disable
            name: coder-db-secret
            key: database-url-alt

  service:
    type: ClusterIP

coderd:
  tls:
    hostSecretName: coder-tls

ingress:
  enable: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts: coder.services.atlantishq.de
  tls:
    enable: true

templates:
  default:
    spec:
      containers:
        - name: coder
          image: codercom/code-server:latest
          imagePullPolicy: IfNotPresent

          command:
            - /bin/sh
            - -c
          args:
            - |
              apt-get update && \
              apt-get install -y openjdk-17-jdk git && \
              code-server \
                --bind-addr 0.0.0.0:8080 \
                --auth none \
                --enable-proposed-api=genuitecllc.codetogether
          ports:
            - containerPort: 8080

          volumeMounts:
            - name: data
              mountPath: /home/coder

      # Init container for extensions
      initContainers:
        - name: code-server-extensions
          image: codercom/code-server:latest
          command:
            - /bin/sh
            - -c
          args:
            - |
              code-server --install-extension redhat.java && \
              code-server --install-extension vscjava.vscode-java-pack && \
              code-server --install-extension eamodio.gitlens && \
              code-server --install-extension genuitecllc.codetogether
          volumeMounts:
            - name: data
              mountPath: /home/coder

      volumes:
        - name: data
          emptyDir: {}
